name: "Multi event pipeline / workflow" # Name of the pipeline
on:
    push: #Event: Whenever a push is made to the repositary on the master branch
        branches:
            - master
            - test
    pull_request: 
        branches:
            - master 
        types:
            - [closed]        
    workflow_dispatch:    
    
               
jobs: 
    on-push: # Job name
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps: # Steps to be executed in the job
            - name: "Running on master push" # Step 1
              run: echo "Running on astr push/ multievent pipeline"    
    on-pull-request:
        if: github.event_name == 'pull_reuest'
        runs-on: ubuntu-latest
        steps: 
            - name: "Running on pull request"  
              run: echo "Running on pull request"  

    on-pull-request-closed:
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        steps: 
            - name: "Running on pull request closed"
            run: echo "Running on pull request closed"
                      
    on-workflow-dispatch: 
        if: github.event_name == 'workflow_dispatch'
        runs-on: ubuntu-latest
        steps: 
            - name: "Running on workflow disptach"
            run: echo "Running on workflow dispatch"
            